config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, skip: :registrable
  root to: 'home#index'

  resources :admin_users
  resources :messages
  resource :passwords, only: [:edit] do
    collection do
      patch 'update'
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :users
    post 'users/sign_in', to: 'users#sign_in'
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  enum message_type:  [ :info , :warning, :news ]

  has_many :admin_users, through: :messages_users
  has_many :messages_users

  attr_accessor :to_all
  attr_accessor :users
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order('text ASC')
    @messages = @messages.page(params[:page])
    authorize!(:read, @messages)
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save

        handle_user_messages
        format.html { redirect_to messages_path }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)

        handle_user_messages
        format.html { redirect_to messages_path}
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_path }
      format.json { head :no_content }
    end
  end

  private

  def handle_user_messages
    if params[:message][:to_all]== '1'

      users = AdminUser.all
      users.each do |user|
        MessagesUser.create(admin_user_id: user.id, message_id: @message.id)
      end
    else

      params[:users].each do |user|
        MessagesUser.create(admin_user_id: user, message_id: @message.id)
      end
    end
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit!
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_for @message, html: { class: 'ui form left'}  do |f|
  .field
    = f.label t('.text')
    .ui.input
      = f.text_area :text, autofocus: 'true'
  .field
    = f.label t('.type_label')
    .ui.input
      = f.select :message_type, Message.message_types.keys.map { |w| [t(w), w]},{:include_blank => t('.type')}, {class: 'ui fluid dropdown search'}
  .field
    = f.label t('.to_all')
    #check_to_all.ui.orange.toggle.checkbox
      = f.check_box :to_all, autocomplete: 'off'
  #users.field
    = f.label t('users')
    .ui.input
      = select_tag :users, options_from_collection_for_select(AdminUser.order(:email),
      :id,:email,@message.admin_users.map{|t| t.id}), multiple: true, class: 'ui fluid dropdown search'

  = f.submit t('.submit'), class: 'ui submit button orange login-btn'

app/views/messages/edit.html.haml
.ui.page.grid
  .sixteen.wide.column
    %h1= t('.header')
    - if @message.errors.any?
      .ui.info.icon.message.notice
        %i.close.icon
        %i.info.icon
        .content
          .header
            Info
          %p
            = pluralize(@message.errors.count, t('.error'))
            = t('.error_message')
            %ul
              - @message.errors.full_messages.each do |msg|
                #li= msg
    = render 'form'

app/views/messages/index.html.haml
.ui.page.grid
  .sixteen.wide.column
    %table.ui.orange.table
      %thead
        %th
          = t('.message')
        %th
      %tbody
        - @messages.each do |message|
          %tr
            %td
              = message.text
            %td.aligned.right{style: 'width: 200px'}
              - if can? :manage, message
                = link_to t('.edit') ,edit_message_path(message),class: 'ui icon button'
                = link_to t('.delete'), message_path(message), method: :delete,class: 'ui icon button red'
    - if @messages.total_pages > 1
      .ui.center.aligned.segment
        = paginate @messages
  .sixteen.wide.column
    - if can? :create, @messages
      = link_to t('.new_message'),new_message_path, class: 'ui button'

app/views/messages/new.html.haml
.ui.page.grid
  .sixteen.wide.column
    %h1= t('.header')
    - if @message.errors.any?
      .ui.info.icon.message.notice
        %i.close.icon
        %i.info.icon
        .content
          .header
            Info
          %p
            = pluralize(@message.errors.count, t('.error'))
            = t('.error_message')
            %ul
              - @message.errors.full_messages.each do |msg|
                #li= msg
    = render 'form'

app/views/messages/show.html.haml
.ui.page.grid
  .sixteen.wide.column
    %h1= t('.header')
    .ui.secondary.segment
      = @message.text