config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, skip: :registrable
  root to: 'home#index'

  resources :admin_users
  resources :messages
  resource :passwords, only: [:edit] do
    collection do
      patch 'update'
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :users
    post 'users/sign_in', to: 'users#sign_in'
  end

end

app/views/shared/_alerts.haml
.ui.page.grid
  .sixteen.wide.column
    - flash.each do |key, value|
      - if key == 'info'
        .ui.teal.icon.message.notice
          %i.close.icon
          %i.info.icon
          .content
            .header
              Info
            %ul.list
              = raw(value)

      - if key == 'message_warning'
        .ui.negative.icon.message.alert
          %i.close.icon
          %i.warning.icon
          .content
            .header
              =t('.message_warning')
            %ul.list
              = raw(value)

      - if key == 'message_news'
        .ui.positive.icon.message.notice
          %i.close.icon
          %i.warning.icon
          .content
            .header
              =t('.message_news')
            %ul.list
              = raw(value)

      - if key == 'message'
        .ui.info.icon.message.notice
          %i.close.icon
          %i.warning.icon
          .content
            .header
              =t('.message')
            %ul.list
              = raw(value)

app/views/shared/_top_menu.haml
.header
  .ui.page.grid
    .sixteen.wide.column
      #menu
        .ui.menu.teal
          = link_to(root_path, class: 'header item') do
            %i.mini.circular.teal.rebel.icon
            Stepfun
          -# - if can? :update, Attendant
            = t('.payments')
            = link_to(attendants_path, class: active_menu(attendants_path, 'item')) do
              %i.bar.icon
              = t('.attendants')
          .right.menu
            - if current_admin_user.companies.length > 1
              = select_tag "company_select", options_from_collection_for_select(current_admin_user.companies,
              "id", "name", selected: session[:company]), multiple: false, class: 'ui dropdown company_select item'
            .ui.dropdown.item.drop
              %i.options.icon
              %i.dropdown.icon
              .menu
                .header
                  = current_admin_user.email
                .divider
                .ui.dropdown.item.drop
                  = t('.language')
                  %i.dropdown.icon
                  .menu
                    = link_to(params.merge(locale: :en), class: 'item') do
                      🇺🇸
                      English
                    = link_to(params.merge(locale: :'pt-BR'), class: 'item') do
                      🇧🇷
                      Português
                - if can?(:manage, AdminUser)
                  = link_to(admin_users_path, class: active_menu(admin_users_path, 'item')) do
                    = t('.users')
                    %i.users.icon.right.floated
                  = link_to(messages_path, class: active_menu(messages_path, 'item')) do
                    = t('.messages')
                    %i.comment.icon.right.floated
                = link_to(edit_passwords_path(@admin_user), class: 'item') do
                  %i.key.icon.right.floated
                  = t('.alter_password')
                = link_to(destroy_admin_user_session_path, method: :delete, class: 'item') do
                  %i.power.icon.right.floated
                  = t('.exit')